#!/usr/bin/env bash

set -e
if [ -e "$HOME/.local" ]; then
    BAK="$HOME/.backups/"$(date +"%Y.%m.%d_%H:%M:%S")
    echo "Backing up $HOME/.local to $BAK"
    cp -r "$HOME/.local" "$BAK"
fi
rm -rf ~/.local/bashrc.d

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
mkdir -p ~/.local/bashrc.d ~/.local/bin
for FN in "${DIR}/bashrc.d"/*; do
    cp "$FN" ~/.local/bashrc.d/
done

for FN in "${DIR}/bin"/*; do
    cp "$FN" ~/.local/bin/
done

touch ~/.local/bashrc.d/000.keep.sh
cat > ~/.bashrc <<'EOF'
# do not edit this file. put files in the dir below.
for FN in $HOME/.local/bashrc.d/*.sh ; do
    source "$FN"
done
EOF
