execute pathogen#infect()

set runtimepath^="~/.vim_go_runtime"
source ~/.vim_go_runtime/vimrc/basic.vim
source ~/.vim_go_runtime/vimrc/filetypes.vim
source ~/.vim_go_runtime/vimrc/plugins.vim
source ~/.vim_go_runtime/vimrc/extended.vim

map 0 0
set relativenumber
set nofoldenable
