set relativenumber
set ruler

set statusline=
set statusline+=%m
set statusline+=\ %f
set statusline+=%=
set statusline+=\ %{LinterStatus()}

set undodir=~/.vim/undo/
set undofile

set backupdir=~/.vim/backup/
set backup
set writebackup

set mouse=a

syntax on

autocmd FileType sh setlocal tabstop=2 shiftwidth=2 expandtab
autocmd FileType python setlocal tabstop=4 shiftwidth=4 expandtab
filetype plugin indent on
autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4 tabstop=4
autocmd FileType python setlocal smartindent autoindent

let g:ale_linters={
\ 'python': ['ruff', 'pyright'],
\}

let g:ale_fixers={
\ 'python': ['ruff'],
\}

let g:ale_fixers={
\ '*':['remove_trailing_lines', 'trim_whitespace'],
\ 'python': ['ruff_format', 'isort'],
\ 'sh': ['shfmt'],
\ 'go': ['gofmt', 'goimports'],
\}

let g:ale_fix_on_save = 1
